DATA:
  PAIRS_NUM_PER_SEQUENCE: 8
  IMG_SIZE: 256
  TASK_TRANSFORM: True
  TASK_TRANSFORM_TYPE: 'random'

MODEL:
  NAME: 'baseline-v2'
  ENCODER:
    FREEZE: False
    WINDOW_SIZE: 7
  DECODER:
    MAX_POSITION_EMBEDDINGS: 8192

TRAIN:
  LOSS_FUNCTION: 'CE+Dice'
  LOSS_WEIGHT: [1,1]
  BASE_LR: 0.002
  WARMUP_LR: 0.00002
  MIN_LR: 0.0002
  WARMUP_EPOCHS: 10
  EPOCHS: 100
  WEIGHT_DECAY: 0.01
  DICE_INCLUDE_BACKGROUND: False
  LOSS_MASK_TYPE: 'segment-predict-last-only'
  PROMPT_NUMBER: 3

TEST:
  SHUFFLE: True
  
VAL_BY_ITER: True
VAL_FREQ: 5000
VAL_ITER: 100
PRINT_FREQ: 50
SAVE_BY_ITER: True
SAVE_FREQ_BY_ITER: 10000
OVERIDE_LR_SCHEDULER: False
ATTENTION_MASK_TYPE: 'image_only_causal'
SEED: 3407
